name: Ruby CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # ou a versão do Ruby que você está usando

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests and generate coverage report
      run: bundle exec rspec calculadora/testes/coverage_report.rb

    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/.resultset.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
