name: Ruby CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        bundle exec rspec calculadora/testes/testes.rb

    - name: List directory contents for debugging
      run: ls -R

    - name: Generate coverage report
      run: |
        if [ -f coverage_report.rb ]; then
          bundle exec ruby coverage_report.rb
        else
          echo "coverage_report.rb not found"
          exit 1
        fi

    - name: Run bundler audit
      run: bundle exec bundler-audit check --update
